# Logging Configuration
**UTCS-MI Code: [080] Logging Configuration**

```yaml
# Logging System Configuration
logging:
  version: "1.0.0"
  global_level: "info"
  
# Log Destinations
destinations:
  console:
    enabled: true
    level: "info"
    format: "structured"
    
  file:
    enabled: true
    path: "/var/log/aqua.log"
    level: "debug"
    rotation: "daily"
    max_size: "100MB"
    
  quantum_log:
    enabled: true
    path: "/var/log/quantum.log"
    level: "info"
    quantum_state_logging: true
    
# Component Logging
components:
  kernel: "info"
  framework: "info"
  platforms: "info"
  security: "warn"
  quantum: "debug"
```