# AQUA OS Boot Configuration
# UTCS-MI Code: [061] Boot Configuration

# Boot System Configuration
boot:
  version: "1.0.0"
  mode: "quantum-aware"  # Options: quantum-aware, classical-only, hybrid
  timeout: 30  # Boot timeout in seconds
  
# Kernel Configuration
kernel:
  image: "mos-kernel.img"
  version: "1.0.0"
  load_address: "0x100000"
  max_memory: "8GB"
  
# Initial RAM Disk
initramfs:
  image: "initramfs.img"
  size: "256MB"
  compression: "lz4"
  
# Quantum Hardware
quantum:
  detection_enabled: true
  timeout: 10  # Quantum detection timeout in seconds
  fallback_mode: "classical"
  required_capabilities:
    - "quantum_gateway"
    - "quantum_memory"
    - "quantum_networking"
  
# Security Settings
security:
  secure_boot: true
  signature_verification: true
  crypto_engine: "post-quantum"
  entropy_source: "quantum"  # fallback to "hardware"
  
# Platform Services
platforms:
  auto_start:
    - "ampel360"
    - "caas"
    - "diqiaas"
    - "gaia"
  
# Framework Services
framework:
  auto_start:
    - "cqea"
    - "amores"
    - "wee"
    - "demos"
    
# Network Configuration
network:
  interfaces:
    - name: "eth0"
      dhcp: true
    - name: "quantum0"
      type: "quantum_network"
      auto_configure: true
      
# Logging
logging:
  level: "info"  # debug, info, warn, error
  destinations:
    - "console"
    - "file:/var/log/aqua-boot.log"
    
# Recovery
recovery:
  enabled: true
  backup_kernel: "mos-kernel-backup.img"
  max_retries: 3
  
# Performance Tuning
performance:
  parallel_init: true
  quantum_preload: true
  cache_optimized: true