# AMPEL360 Platform Configuration
# UTCS-MI Code: [415] Platform Configuration

# Platform Information
platform:
  name: "AMPEL360"
  version: "1.0.0"
  type: "comprehensive_platform"
  description: "Comprehensive aerospace and quantum platform infrastructure"
  
# Core Services
core_services:
  authentication:
    enabled: true
    type: "multi_factor"
    quantum_keys: true
    
  authorization:
    enabled: true
    model: "rbac"  # Role-Based Access Control
    quantum_permissions: true
    
  service_mesh:
    enabled: true
    protocol: "grpc"
    encryption: "post_quantum"
    
  api_gateway:
    enabled: true
    port: 8080
    tls: true
    rate_limiting: true
    
  monitoring:
    enabled: true
    metrics_interval: 30  # seconds
    health_checks: true
    
  discovery:
    enabled: true
    service_registry: "consul"
    health_checking: true
    
  configuration:
    enabled: true
    source: "distributed"
    encryption: true

# Resource Allocation
resources:
  cpu_cores: 8
  memory_gb: 32
  storage_gb: 1000
  quantum_qubits: 1000
  network_bandwidth_gbps: 10
  
# Scaling Configuration
scaling:
  auto_scaling: true
  min_instances: 1
  max_instances: 10
  scale_up_threshold: 80   # CPU percentage
  scale_down_threshold: 20 # CPU percentage
  
# Security Configuration
security:
  level: "maximum"
  encryption: "post_quantum"
  key_rotation_hours: 24
  audit_all_access: true
  quantum_safe_protocols: true
  
# Network Configuration
network:
  interfaces:
    - name: "management"
      type: "ethernet"
      port: 8080
    - name: "quantum"
      type: "quantum_network"
      port: 9090
    - name: "inter_platform"
      type: "mesh"
      port: 8081
      
# Data Management
data:
  storage_type: "distributed"
  replication_factor: 3
  encryption: "quantum_safe"
  backup_enabled: true
  backup_interval_hours: 6
  
# Integration Points
integration:
  cqea_framework: true
  amores_compliance: true
  wee_learning: true
  demos_monitoring: true
  
# Platform-Specific Settings
platform_specific:
  aerospace_compliance: true
  quantum_optimization: true
  real_time_processing: true
  fault_tolerance: "triple_redundancy"
  
# Development and Testing
development:
  debug_mode: false
  test_endpoints: false
  performance_profiling: true
  
# Logging
logging:
  level: "info"
  destinations:
    - "console"
    - "file:/var/log/ampel360.log"
    - "metrics_collector"
  structured_logging: true
  
# Health Checks
health_checks:
  enabled: true
  interval_seconds: 30
  timeout_seconds: 10
  endpoints:
    - "/health"
    - "/readiness"
    - "/liveness"
    
# Performance Targets
performance:
  max_response_time_ms: 100
  max_startup_time_s: 30
  min_availability_percent: 99.9
  max_error_rate_percent: 0.1