# AQUA OS Global Configuration
# Main system configuration file

# System Information
system:
  name: "AQUA OS"
  version: "1.0.0"
  build: "2025.001"
  architecture: "quantum-classical-hybrid"
  
# Boot Configuration
boot:
  auto_start_services: true
  quantum_detection: true
  security_mode: "maximum"
  
# Kernel Configuration
kernel:
  name: "MOS"
  scheduler: "quantum-aware-cfs"
  memory_management: "quantum-classical-unified"
  security: "post-quantum"
  
# Framework Configuration
framework:
  cqea_enabled: true
  amores_enabled: true
  wee_enabled: true
  demos_enabled: true
  
# Platform Configuration
platforms:
  ampel360:
    enabled: true
    auto_start: true
    config_file: "platforms/ampel360/config/platform-config.yaml"
  caas:
    enabled: true
    auto_start: true
    config_file: "platforms/caas/caas-config.yaml"
  diqiaas:
    enabled: true
    auto_start: true
    config_file: "platforms/diqiaas/diqiaas-config.yaml"
  gaia:
    enabled: true
    auto_start: true
    config_file: "platforms/gaia/gaia-config.yaml"
    
# Global Security Settings
security:
  encryption: "post-quantum"
  key_management: "quantum-safe"
  authentication: "multi-factor"
  authorization: "role-based"
  audit_logging: true
  
# Quantum Configuration
quantum:
  hardware_detection: true
  fallback_simulation: true
  error_correction: true
  max_qubits: 1000000
  gate_fidelity_threshold: 0.99
  
# Network Configuration
network:
  quantum_networking: true
  classical_protocols: ["tcp", "udp", "http", "https"]
  quantum_protocols: ["qkd", "quantum_internet"]
  
# Storage Configuration
storage:
  filesystem: "aqua-fs"
  encryption: "quantum-safe"
  compression: true
  deduplication: true
  
# Monitoring and Logging
monitoring:
  enabled: true
  metrics_collection: true
  performance_monitoring: true
  health_checks: true
  
logging:
  level: "info"
  destinations:
    - "console"
    - "file:/var/log/aqua.log"
    - "syslog"
  quantum_events: true
  
# Integration Settings
integration:
  global_integration: true
  system_integration: true
  platform_integration: true
  domain_integration: true
  
# Development and Testing
development:
  debug_mode: false
  test_mode: false
  profiling: false
  
# Standards Compliance
standards:
  utcs_mi_version: "5.0"
  aerospace_standards: ["DO-178C", "DO-254", "AS9100"]
  quantum_standards: ["NIST-PQC", "ISO-23053"]
  cybersecurity_standards: ["ISO-27001", "NIST-CSF"]
  
# Resource Limits
limits:
  max_processes: 1024
  max_quantum_processes: 256
  max_memory_gb: 64
  max_quantum_qubits: 1000000
  max_network_connections: 10000