# Boot Configuration
# UTCS-MI Code: [061] Boot Configuration

# AQUA OS Boot Configuration
version: "1.0.0"
specification: "UTCS-MI-061"

# System Configuration
system:
  architecture: "x86_64"
  boot_mode: "uefi"
  secure_boot: true
  tpm_required: true
  
# Kernel Configuration
kernel:
  image: "mos-kernel.img"
  load_address: "0x1000000"
  entry_point: "0x1000400"
  command_line: "root=/dev/ram0 rw quantum_enabled=1"
  
# Memory Configuration
memory:
  limit_mb: 8192
  reserved_quantum_mb: 512
  kernel_heap_mb: 256
  user_space_mb: 4096
  
# Quantum Hardware Detection
quantum:
  detection_enabled: true
  timeout_ms: 5000
  fallback_classical: true
  supported_backends:
    - "qiskit"
    - "cirq"
    - "pennylane"
  hardware_interfaces:
    - "quantum_gates"
    - "quantum_sensors"
    - "quantum_memory"
    
# Security Configuration
security:
  post_quantum_crypto: true
  key_exchange: "kyber768"
  signature_algorithm: "dilithium3"
  hash_algorithm: "sha3-256"
  secure_enclave: true
  
# Boot Services
services:
  - name: "quantum_detection"
    enabled: true
    priority: 1
  - name: "crypto_init"
    enabled: true
    priority: 2
  - name: "memory_init"
    enabled: true
    priority: 3
  - name: "device_enumeration"
    enabled: true
    priority: 4
    
# Logging Configuration
logging:
  level: "INFO"
  destinations:
    - "serial"
    - "memory_buffer"
  max_buffer_size: "1MB"
  
# Recovery Configuration
recovery:
  enabled: true
  backup_kernel: "mos-kernel-recovery.img"
  recovery_partition: "/dev/sda3"
  auto_recovery: true
  
# Debugging
debug:
  enabled: false
  early_console: true
  verbose_boot: false
  kernel_debug_symbols: false