# Power Configuration
**UTCS-MI Code: [092] Power Configuration**

```yaml
# Power Management Configuration
power:
  version: "1.0.0"
  management_level: "advanced"
  
# Classical Power Management
classical:
  acpi_enabled: true
  dynamic_frequency_scaling: true
  cpu_governors: ["performance", "powersave", "ondemand"]
  sleep_states: ["S1", "S3", "S4", "S5"]
  
# Quantum Power Management  
quantum:
  low_power_mode: true
  coherence_power_optimization: true
  qubit_power_gating: true
  quantum_idle_detection: true
  
# Thermal Management
thermal:
  max_temp_celsius: 85
  quantum_cooling_required: true
  thermal_throttling: true
  fan_control: "automatic"
```